name:                forge
version:             0.3.0.0
github:              "denibertovic/forge"
license:             LGPL-3
author:              "Deni Bertovic"
maintainer:          "deni@denibertovic.com"
copyright:           "2018 Deni Bertovic"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/denibertovic/forge#readme>

ghc-options:
# - -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- rio
- text
- bytestring
- yaml
- optparse-applicative
- aeson
- filepath
- filemanip
- directory
- conduit
- tar-conduit
- conduit-extra
- unix
- http-client
- http-conduit
- http-types
- http-client-tls
- http-conduit
- pretty-simple
- typed-process

library:
  source-dirs: src

default-extensions:
  - NoImplicitPrelude

executables:
  forge:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forge

tests:
  forge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forge
