name:                forge
version:             0.1.0.0
github:              "denibertovic/forge"
license:             BSD3
author:              "Deni Bertovic"
maintainer:          "deni@denibertovic.com"
copyright:           "2018 Deni Bertovic"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/denibertovic/forge#readme>

dependencies:
- base >= 4.7 && < 5
- yaml
- optparse-applicative
- text
- aeson
- directory
- unix
- bytestring
- http-types
- http-client
- http-client-tls
- http-conduit

library:
  source-dirs: src

executables:
  forge:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forge

tests:
  forge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forge
